### ISSUE TITLE
Poetry install fails

### ISSUE THREAD

**Issue by kasasxav** [CEA-MetroCarac/pystack3d#3]
Hi,

I am trying to install pystack3d to test it for the [review at JOSS](https://github.com/openjournals/joss-reviews/issues/7079#issuecomment-2324619118), but when I try "poetry install" it fails with:

~/github/pystack3d$ poetry install

[tool.poetry] section not found in [...]/pystack3d/pyproject.toml
 
I'm using linux, do you know which could be the problem?

**Comment by patquem** [comment]
Hi @kasasxav ,

I have (hopefully) fixed this.

Instead of :
```
pip install poetry
poetry install
```
Just do:
`pip install . `

It should work.
