### ISSUE TITLE
ModuleNotFound error

### ISSUE THREAD

**Issue by kasasxav** [CEA-MetroCarac/pystack3d#4]
Hi,

When I try to run the tests (either from the main folder or from the tests folder) for the [review](https://github.com/openjournals/joss-reviews/issues/7079#issuecomment-2325281666), I get this error:
from examples.ex_synthetic_stack import ex_synthetic_stack as ex_synth
examples/ex_synthetic_stack.py:18: in <module>
    from utils import init_dir, postpro, plot_results, plot_cube_faces
E   ModuleNotFoundError: No module named 'utils'

I think it might be solved by adding init files.

**Comment by kasasxav** [comment]
Hi, 

I see that another reviewer commented on this error and you didn't manage to fix it yet.
I think it's quite simple, I added "import utils" or "from utils import *" in the init file and it worked.

But I saw the init file is super long though, normally you only import the necessary packages. Is there a way that the code is moved to another file? And initialized when the user instanciates Stack3d?

**Comment by kasasxav** [comment]
Hi,

I see that another reviewer commented and you didn't manage to fix it. I tried and fixed it by changing: 
from utils import...
to:
from examples.utils import ...

By the way the init file in pystack3d is quite large, and init files are usually just used for the imports. Is there a way that all of the code can be moved to the point when the user initialized Stack3D() ?

**Comment by patquem** [comment]
@kasasxav , I've made the changes you mentioned. Everything is fine (the tests passed). Many thanks.

**Comment by kasasxav** [comment]
ah sorry, but then if you try to run it from examples it doesn't work.

You could try:

try:
   from utils import ...
 except ModuleNotFoundError:
 from examples.utils import ...

**Comment by patquem** [comment]
My IDE is PyCharm, which automatically adds some paths to the PYTHONPATH, making it harder to spot issues like this. The try/except solution you suggested seems like a good approach. I’ll update the package accordingly
